name       : python-mypy
version    : '0.710'
release    : 2
source     :
    - https://github.com/python/mypy/archive/v0.710.tar.gz : 5545e922d3e51bad1e4aa820f211e45ebcc576bd587e247303c04ea125018dd6
license    : MIT
component  : programming.python
summary    : Optional static typing for Python 3 (PEP484)
description: |
    Add type annotations to your Python programs, and use mypy to type check them.
    Mypy is essentially a Python linter.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
