name       : python-mypy
version    : '0.941'
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/m/mypy/mypy-0.941.tar.gz : cbcc691d8b507d54cb2b8521f0a2a3d4daa477f62fe77f0abba41e5febb377b7
homepage   : http://www.mypy-lang.org/
license    : MIT
component  : programming.python
summary    : Optional static typing for Python 3 (PEP484)
description: |
    Mypy is an optional static type checker for Python that aims to combine the benefits of dynamic (or "duck") typing and static typing. Mypy combines the expressive power and convenience of Python with a powerful type system and compile-time type checking. Mypy type checks standard Python programs; run them using any Python VM with basically no runtime overhead.
rundeps    :
    - python-mypy_extensions
    - python-tomli
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
