name       : python-mypy
version    : 0.711
release    : 4
source     :
    - https://github.com/python/mypy/archive/v0.711.tar.gz : f8610919b196f5c349214709bd50ba544efaf368099ba87a3956eb75fd4936c9
license    : MIT
component  : programming.python
summary    : Optional static typing for Python 3 (PEP484)
description: |
    Add type annotations to your Python programs, and use mypy to type check them.
    Mypy is essentially a Python linter.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
