name       : python-mypy
version    : '0.782'
release    : 7
source     :
    - https://files.pythonhosted.org/packages/60/18/8586a7706781744aaa805dda4568fab4f0944455486822d7318e4dcee2bc/mypy-0.782.tar.gz : eff7d4a85e9eea55afa34888dfeaccde99e7520b51f867ac28a48492c0b1130c
homepage   : http://www.mypy-lang.org/
license    : MIT
component  : programming.python
summary    : Optional static typing for Python 3 (PEP484)
description: |
    Mypy is an optional static type checker for Python that aims to combine the benefits of dynamic (or "duck") typing and static typing. Mypy combines the expressive power and convenience of Python with a powerful type system and compile-time type checking. Mypy type checks standard Python programs; run them using any Python VM with basically no runtime overhead.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-mypy_extensions
    - python-typed-ast
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
