name       : python-mypy
version    : '0.790'
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/m/mypy/mypy-0.790.tar.gz : 2b21ba45ad9ef2e2eb88ce4aeadd0112d0f5026418324176fd494a6824b74975
homepage   : http://www.mypy-lang.org/
license    : MIT
component  : programming.python
summary    : Optional static typing for Python 3 (PEP484)
description: |
    Mypy is an optional static type checker for Python that aims to combine the benefits of dynamic (or "duck") typing and static typing. Mypy combines the expressive power and convenience of Python with a powerful type system and compile-time type checking. Mypy type checks standard Python programs; run them using any Python VM with basically no runtime overhead.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-mypy_extensions
    - python-typed-ast
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
