name       : python-mypy
version    : 0.641
release    : 1
source     :
    - https://files.pythonhosted.org/packages/a1/b9/e2063c8f933c1cfebef5dcd7325e07b927cf5a5cef60772aaad5eb903a0f/mypy-0.641.tar.gz : 8e071ec32cc226e948a34bbb3d196eb0fd96f3ac69b6843a5aff9bd4efa14455
license    : MIT
component  : programming.python
summary    : Optional static typing for Python 3 (PEP484)
description: |
    Add type annotations to your Python programs, and use mypy to type check them.
    Mypy is essentially a Python linter.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install